# https://octokit.github.io/rest.js
# https://github.com/actions/toolkit/blob/master/packages/github/src/context.ts

name: Pull Request
on: pull_request

jobs:
  mandatory-changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install packages
        run: npm install --only=dev

      - name: Validate
        run: |
          node ./.github/workflows/on-pr.js mandatoryChanges